{
  "hash": "0e69ff86c5b7fa15241d0d2d1545827e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Which Tech Skills Should I Learn? Evidence from Arbeitnow Jobs\"\ndescription: \"A reproducible R scrape turns German-focused job postings into role-specific study priorities.\"\ndate: \"2026-09-21\"\ncategories: [web-scraping, R, labor-market]\nformat:\n  html:\n    toc: true\n    code-fold: true\nexecute:\n  echo: false\n---\n\n\n\n## A career decision, not just a word count\n\nLearning a new tool takes time. For someone interested in a software, data, or IT job, should the next project use Python, TypeScript, a cloud platform, or something else? Does the board offer remote or entry-level opportunities? Job advertisements offer practical clues. I used [Arbeitnow](https://www.arbeitnow.com/), a Germany-focused job board, to examine **skills, role types, work arrangement, and experience level**.\n\n## From public pages to clean data\n\nOn September 21, 2026, my [R collection script](code/01_scrape_jobs.R) used `rvest` to read 100 public listing pages. It saved their HTML and extracted 5000 unique job titles and URLs. Of those titles, 1019 matched a documented software, data, or IT role pattern. Arbeitnow also offers a [public job-board API](https://www.arbeitnow.com/blog/job-board-api) with full descriptions; collecting its paginated feed avoided requesting thousands of individual job pages. The API ended after 29 pages of jobs and supplied 3153 unique descriptions, of which 543 matched the technology-role pattern. 1836 API jobs also appeared in the 100-page HTML snapshot. The two sources are snapshots of the same changing board, so their page lists do not line up exactly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rvest)\npage <- read_html(\"data/raw/html/page-001.html\")\nlinks <- html_elements(page, \"a[data-job-item-link]\")\njob_urls <- html_attr(links, \"href\")\njob_titles <- html_text2(links)\n```\n:::\n\n\nThe [API pagination helper](code/extend_api_cache.R) manages the paced feed requests. The separate [analysis script](code/02_analyze_jobs.R) cleans description HTML, removes duplicate URLs, and searches for 20 named technologies. It counts a skill once per job even when the word appears repeatedly. **Every skill percentage below divides by the 543 technology jobs with descriptions**, not by all HTML listings. The scripts save the cleaned data, tables, and figures; the [README](README.md) gives replication commands. The complete project is in the [GitHub repository](https://github.com/liu118-oss/AEDS-6400-Blog). Collection used sequential requests with pauses, followed the site's [robots.txt](https://www.arbeitnow.com/robots.txt), and used no login or access workaround. Arbeitnow's [API terms](https://www.arbeitnow.com/terms) ask users to link back to the site.\n\n## Which skills appear most often?\n\n\n::: {#tbl-top-skills .cell tbl-cap='Most frequently mentioned technologies among 543 technology job descriptions. Postings can mention more than one skill.'}\n::: {.cell-output-display}\n\n\n|Skill      | Postings|Share of technology postings |\n|:----------|--------:|:----------------------------|\n|Python     |      187|34.4%                        |\n|AWS        |      114|21%                          |\n|Git        |      108|19.9%                        |\n|Kubernetes |       91|16.8%                        |\n|TypeScript |       91|16.8%                        |\n|Docker     |       88|16.2%                        |\n|SQL        |       86|15.8%                        |\n\n\n:::\n:::\n\n\n![Bar chart ranking named technologies by the share of technology postings mentioning them.](results/skill_frequencies.png)\n\nPython appears in 187 postings (34.4%), followed by AWS in 114 (21%) and Git in 108 (19.9%). Python and Git appear together in 64 postings. These are **mentions**, not proof that every employer requires the skill. Percentages do not sum to 100 because one posting can name several technologies.\n\nThe overall ranking hides important differences. My title-based groups contain 325 software development, 161 infrastructure or security, and 57 data or machine-learning postings. The two most frequently named skills in each group are:\n\n\n::: {#tbl-role-skills .cell tbl-cap='Top two skill mentions within each role group. Percentages use the number of jobs in that group.'}\n::: {.cell-output-display}\n\n\n|Role group                |Skill      | Postings|Within-group share |\n|:-------------------------|:----------|--------:|:------------------|\n|Data / ML                 |Python     |       49|86%                |\n|Data / ML                 |SQL        |       32|56.1%              |\n|Infrastructure / security |Kubernetes |       42|26.1%              |\n|Infrastructure / security |Python     |       41|25.5%              |\n|Software development      |Python     |       97|29.8%              |\n|Software development      |TypeScript |       78|24%                |\n\n\n:::\n:::\n\n\n## Work arrangement and experience level\n\nOnly 42 of the 543 technology jobs (7.7%) are **marked remote**. The other 501 have `remote = FALSE` in the source. That means *not marked remote*; it does not prove they require full-time office attendance. Remote shares are 9.9% for infrastructure and security, 7.4% for software development, and 3.5% for data and machine learning. The last figure comes from just 2 remote postings, so I would not infer a stable difference between fields.\n\n![Bar chart of the percentage of each technology role group marked remote in the Arbeitnow API.](results/remote_by_role.png)\n\nExperience is another constraint: 198 postings (36.5%) include a senior or lead term in the title, while only 41 (7.6%) include an early-career term. The rest do not state a clear level in the title. An entry-level or remote job seeker should therefore filter listings by those needs **before** using the overall skill ranking to plan a project.\n\n## What should a job seeker do?\n\nIf I were targeting **data or machine-learning roles**, I would build a Python project that queries and analyzes data with SQL: those two skills appear in 49 of 57 data postings and 32 of them, respectively. For **software development**, I would show Python or TypeScript in a working application. For **infrastructure**, I would demonstrate deploying and monitoring an application with Kubernetes or a cloud service. These projects provide evidence of ability rather than a list of keywords on a résumé.\n\nThe sample has limits. Arbeitnow is one board, many jobs are Germany-focused, and the title filter may miss relevant roles. A technology mentioned in company background or as a preference is still counted. Only 378 of the 543 technology postings mention one of my 20 chosen terms, so the dictionary is incomplete. This analysis measures current advertised language, not hiring outcomes or the return to learning a skill.\n\n## Takeaway\n\nThe useful lesson is to choose a **role and work arrangement first**, then use job descriptions to prioritize a small, demonstrable set of skills. Python is the broadest starting point here, but SQL, TypeScript, and Kubernetes matter differently across roles. Remote and early-career openings are a small, specifically labeled part of this sample. Check target postings before investing in a course, and repeat the analysis as listings change.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}